"""
eod_summary.py — runs at 4:30pm ET weekdays via GitHub Actions.
Reads the final data.js and data_prev.js to compute the end-of-day digest,
writing eod_data.js for the EOD Summary tab.
"""

import json
import re
import os
from datetime import datetime, timezone


def load_data(path):
    if not os.path.exists(path):
        return None
    with open(path) as f:
        content = f.read()
    match = re.search(r"const DATA = ({[\s\S]+});", content)
    if not match:
        return None
    return json.loads(match.group(1))


def main():
    data = load_data("data.js")
    prev = load_data("data_prev.js")

    if not data:
        print("data.js not found — aborting.")
        return

    stocks = data.get("stocks", [])
    prev_stocks = {s["ticker"]: s for s in (prev.get("stocks", []) if prev else [])}

    # Top gainers / losers by composite score change vs previous session
    score_moves = []
    for s in stocks:
        prev_score = prev_stocks.get(s["ticker"], {}).get("compositeScore", s["compositeScore"])
        delta = round(s["compositeScore"] - prev_score, 1)
        score_moves.append({**s, "scoreDelta": delta})

    score_moves.sort(key=lambda x: x["scoreDelta"], reverse=True)
    top_risers = score_moves[:5]
    top_fallers = list(reversed(score_moves[-5:]))

    # Price movers by 1M momentum proxy
    by_momentum = sorted(stocks, key=lambda x: x["signals"].get("momentum1m", 0), reverse=True)
    price_gainers = by_momentum[:5]
    price_losers = list(reversed(by_momentum[-5:]))

    # Market breadth from scores
    strong_buy = sum(1 for s in stocks if s["compositeScore"] >= 75)
    buy = sum(1 for s in stocks if 60 <= s["compositeScore"] < 75)
    hold = sum(1 for s in stocks if 40 <= s["compositeScore"] < 60)
    sell = sum(1 for s in stocks if 25 <= s["compositeScore"] < 40)
    strong_sell = sum(1 for s in stocks if s["compositeScore"] < 25)

    avg_composite = round(sum(s["compositeScore"] for s in stocks) / len(stocks), 1) if stocks else 0

    def slim(s):
        return {
            "ticker": s["ticker"],
            "name": s["name"],
            "sector": s["sector"],
            "compositeScore": s["compositeScore"],
            "scoreDelta": s.get("scoreDelta", 0),
            "momentum3m": s["signals"].get("momentum3m", 0),
        }

    now_utc = datetime.now(timezone.utc)
    payload = {
        "date": now_utc.strftime("%Y-%m-%d"),
        "generatedAt": now_utc.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "topPick": data.get("topPick", {}),
        "scoreRisers": [slim(s) for s in top_risers],
        "scoreFallers": [slim(s) for s in top_fallers],
        "priceGainers": [slim(s) for s in price_gainers],
        "priceLosers": [slim(s) for s in price_losers],
        "breadth": {
            "strongBuy": strong_buy,
            "buy": buy,
            "hold": hold,
            "sell": sell,
            "strongSell": strong_sell,
            "avgComposite": avg_composite,
        },
        "sectors": data.get("sectors", {}),
    }

    with open("eod_data.js", "w") as f:
        f.write("// Auto-generated by eod_summary.py — do not edit manually\n")
        f.write(f"const EOD_DATA = {json.dumps(payload, indent=2)};\n")

    print(f"eod_data.js written for {now_utc.strftime('%Y-%m-%d')} — top pick: {data.get('topPick', {}).get('ticker', 'N/A')}")


if __name__ == "__main__":
    main()
