// Auto-generated by eod_summary.py — do not edit manually
const EOD_DATA = {
  "date": "2026-08-03",
  "generatedAt": "2026-08-03T22:10:41Z",
  "topPick": {
    "ticker": "VLO",
    "name": "Valero Energy",
    "sector": "Energy",
    "price": 307.54,
    "changePct": 0.68,
    "compositeScore": 81.2,
    "technicalScore": 43.4,
    "fundamentalScore": 90.9,
    "momentumScore": 92.2,
    "sectorScore": 100.0,
    "rank": 1,
    "prevRank": 1,
    "signals": {
      "rsi": 55.0,
      "macd": "bearish",
      "bbPct": 0.668,
      "ma50": 270.44,
      "ma200": 217.22,
      "volRatio": 0.92,
      "pe": 13.05,
      "sectorPe": 20.1,
      "epsGrowth": 4.535,
      "revGrowth": 0.517,
      "fcfYield": 0.0934,
      "roe": 0.2764,
      "debtEquity": 0.4015,
      "momentum1m": 14.21,
      "momentum3m": 23.27,
      "momentum6m": 73.17,
      "sectorOutperf3m": 23.57
    },
    "thesis": "Valero Energy (VLO) is trading at 13.1x P/E, a 35% discount to its sector average of 20.1x; RSI at 55 reflects healthy bullish momentum without overextension. Three-month price momentum of +23.3% reflects exceptional institutional accumulation, with EPS growing +454% year-on-year, underpinned by a bearish MACD signal suggesting near-term caution is warranted. Composite score of 81/100 places VLO in the top 1% of S&P 500 constituents across all four analytical strategies, outperforming its sector by +23.6% over the past quarter."
  },
  "scoreRisers": [
    {
      "ticker": "BXP",
      "name": "BXP, Inc.",
      "sector": "Real Estate",
      "compositeScore": 56.1,
      "scoreDelta": 3.1,
      "momentum3m": 21.46
    },
    {
      "ticker": "KVUE",
      "name": "Kenvue",
      "sector": "Consumer Staples",
      "compositeScore": 59.8,
      "scoreDelta": 2.2,
      "momentum3m": 12.18
    },
    {
      "ticker": "MKC",
      "name": "McCormick & Company",
      "sector": "Consumer Staples",
      "compositeScore": 53.9,
      "scoreDelta": 2.1,
      "momentum3m": 8.26
    },
    {
      "ticker": "TDG",
      "name": "TransDigm Group",
      "sector": "Industrials",
      "compositeScore": 50.8,
      "scoreDelta": 2.1,
      "momentum3m": 11.82
    },
    {
      "ticker": "PCAR",
      "name": "Paccar",
      "sector": "Industrials",
      "compositeScore": 55.3,
      "scoreDelta": 2.0,
      "momentum3m": 15.83
    }
  ],
  "scoreFallers": [
    {
      "ticker": "VTR",
      "name": "Ventas",
      "sector": "Real Estate",
      "compositeScore": 44.1,
      "scoreDelta": -2.7,
      "momentum3m": 4.09
    },
    {
      "ticker": "SCHW",
      "name": "Charles Schwab Corporation",
      "sector": "Financials",
      "compositeScore": 57.0,
      "scoreDelta": -2.4,
      "momentum3m": 16.15
    },
    {
      "ticker": "MCK",
      "name": "McKesson Corporation",
      "sector": "Health Care",
      "compositeScore": 45.1,
      "scoreDelta": -1.7,
      "momentum3m": 2.5
    },
    {
      "ticker": "MRNA",
      "name": "Moderna",
      "sector": "Health Care",
      "compositeScore": 52.7,
      "scoreDelta": -1.7,
      "momentum3m": 16.58
    },
    {
      "ticker": "FSLR",
      "name": "First Solar",
      "sector": "Information Technology",
      "compositeScore": 53.7,
      "scoreDelta": -1.7,
      "momentum3m": 10.1
    }
  ],
  "priceGainers": [
    {
      "ticker": "CTSH",
      "name": "Cognizant",
      "sector": "Information Technology",
      "compositeScore": 49.1,
      "scoreDelta": 0,
      "momentum3m": 7.13
    },
    {
      "ticker": "PYPL",
      "name": "PayPal",
      "sector": "Financials",
      "compositeScore": 60.3,
      "scoreDelta": 0,
      "momentum3m": 15.22
    },
    {
      "ticker": "MSFT",
      "name": "Microsoft",
      "sector": "Information Technology",
      "compositeScore": 63.1,
      "scoreDelta": 0,
      "momentum3m": 18.15
    },
    {
      "ticker": "BAX",
      "name": "Baxter International",
      "sector": "Health Care",
      "compositeScore": 69.9,
      "scoreDelta": 0,
      "momentum3m": 69.16
    },
    {
      "ticker": "GRMN",
      "name": "Garmin",
      "sector": "Consumer Discretionary",
      "compositeScore": 69.1,
      "scoreDelta": 0,
      "momentum3m": 28.29
    }
  ],
  "priceLosers": [
    {
      "ticker": "MRNA",
      "name": "Moderna",
      "sector": "Health Care",
      "compositeScore": 52.7,
      "scoreDelta": 0,
      "momentum3m": 16.58
    },
    {
      "ticker": "SNDK",
      "name": "Sandisk",
      "sector": "Information Technology",
      "compositeScore": 53.6,
      "scoreDelta": 0,
      "momentum3m": 2.56
    },
    {
      "ticker": "INTC",
      "name": "Intel",
      "sector": "Information Technology",
      "compositeScore": 46.3,
      "scoreDelta": 0,
      "momentum3m": -4.99
    },
    {
      "ticker": "APP",
      "name": "AppLovin",
      "sector": "Information Technology",
      "compositeScore": 34.7,
      "scoreDelta": 0,
      "momentum3m": -14.49
    },
    {
      "ticker": "GLW",
      "name": "Corning Inc.",
      "sector": "Information Technology",
      "compositeScore": 41.3,
      "scoreDelta": 0,
      "momentum3m": -8.19
    }
  ],
  "breadth": {
    "strongBuy": 3,
    "buy": 107,
    "hold": 283,
    "sell": 106,
    "strongSell": 4,
    "avgComposite": 50.2
  },
  "sectors": {
    "Consumer Staples": {
      "avgScore": 48.9,
      "topStock": "DLTR",
      "stockCount": 34,
      "etf": "XLP",
      "etfReturn1m": 0.9,
      "etfReturn3m": 2.28
    },
    "Materials": {
      "avgScore": 49.0,
      "topStock": "CF",
      "stockCount": 26,
      "etf": "XLB",
      "etfReturn1m": -1.87,
      "etfReturn3m": 1.09
    },
    "Consumer Discretionary": {
      "avgScore": 48.4,
      "topStock": "BBY",
      "stockCount": 47,
      "etf": "XLY",
      "etfReturn1m": 0.17,
      "etfReturn3m": 0.62
    },
    "Information Technology": {
      "avgScore": 52.4,
      "topStock": "DELL",
      "stockCount": 74,
      "etf": "XLK",
      "etfReturn1m": -3.01,
      "etfReturn3m": 10.0
    },
    "Energy": {
      "avgScore": 52.6,
      "topStock": "VLO",
      "stockCount": 21,
      "etf": "XLE",
      "etfReturn1m": 10.65,
      "etfReturn3m": -0.3
    },
    "Financials": {
      "avgScore": 54.0,
      "topStock": "ALL",
      "stockCount": 76,
      "etf": "XLF",
      "etfReturn1m": 2.21,
      "etfReturn3m": 11.63
    },
    "Health Care": {
      "avgScore": 51.9,
      "topStock": "DVA",
      "stockCount": 59,
      "etf": "XLV",
      "etfReturn1m": 0.17,
      "etfReturn3m": 12.59
    },
    "Real Estate": {
      "avgScore": 49.4,
      "topStock": "ARE",
      "stockCount": 31,
      "etf": "XLRE",
      "etfReturn1m": 2.01,
      "etfReturn3m": 3.39
    },
    "Utilities": {
      "avgScore": 45.4,
      "topStock": "EIX",
      "stockCount": 31,
      "etf": "XLU",
      "etfReturn1m": -2.08,
      "etfReturn3m": -3.72
    },
    "Communication Services": {
      "avgScore": 46.2,
      "topStock": "GOOG",
      "stockCount": 23,
      "etf": "XLC",
      "etfReturn1m": 1.03,
      "etfReturn3m": -3.85
    },
    "Industrials": {
      "avgScore": null,
      "topStock": "DAL",
      "stockCount": 81,
      "etf": "XLI",
      "etfReturn1m": -1.29,
      "etfReturn3m": 7.39
    }
  }
};
