// Auto-generated by eod_summary.py — do not edit manually
const EOD_DATA = {
  "date": "2026-08-07",
  "generatedAt": "2026-08-07T21:40:14Z",
  "topPick": {
    "ticker": "VLO",
    "name": "Valero Energy",
    "sector": "Energy",
    "price": 298.31,
    "changePct": 0.32,
    "compositeScore": 84.1,
    "technicalScore": 60.5,
    "fundamentalScore": 90.7,
    "momentumScore": 87.0,
    "sectorScore": 100.0,
    "rank": 1,
    "prevRank": 1,
    "signals": {
      "rsi": 37.6,
      "macd": "bearish",
      "bbPct": 0.273,
      "ma50": 275.36,
      "ma200": 220.17,
      "volRatio": 0.75,
      "pe": 12.61,
      "sectorPe": 16.5,
      "epsGrowth": 4.535,
      "revGrowth": 0.517,
      "fcfYield": 0.0965,
      "roe": 0.2764,
      "debtEquity": 0.4015,
      "momentum1m": 6.69,
      "momentum3m": 24.82,
      "momentum6m": 48.45,
      "sectorOutperf3m": 20.84
    },
    "thesis": "Valero Energy (VLO) is trading at 12.6x P/E, a 24% discount to its sector average of 16.5x; RSI at 38 indicates recovering momentum from recent lows. Three-month price momentum of +24.8% reflects exceptional institutional accumulation, with EPS growing +454% year-on-year, underpinned by a bearish MACD signal suggesting near-term caution is warranted. Composite score of 84/100 places VLO in the top 1% of S&P 500 constituents across all four analytical strategies, outperforming its sector by +20.8% over the past quarter."
  },
  "scoreRisers": [
    {
      "ticker": "WST",
      "name": "West Pharmaceutical Services",
      "sector": "Health Care",
      "compositeScore": 51.8,
      "scoreDelta": 2.8,
      "momentum3m": 8.71
    },
    {
      "ticker": "AES",
      "name": "AES Corporation",
      "sector": "Utilities",
      "compositeScore": 50.0,
      "scoreDelta": 2.6,
      "momentum3m": 4.02
    },
    {
      "ticker": "TDG",
      "name": "TransDigm Group",
      "sector": "Industrials",
      "compositeScore": 39.4,
      "scoreDelta": 2.6,
      "momentum3m": 0.84
    },
    {
      "ticker": "DD",
      "name": "DuPont",
      "sector": "Materials",
      "compositeScore": 42.6,
      "scoreDelta": 2.1,
      "momentum3m": -4.18
    },
    {
      "ticker": "GPN",
      "name": "Global Payments",
      "sector": "Financials",
      "compositeScore": 66.6,
      "scoreDelta": 1.5,
      "momentum3m": 24.95
    }
  ],
  "scoreFallers": [
    {
      "ticker": "AIG",
      "name": "American International Group",
      "sector": "Financials",
      "compositeScore": 43.3,
      "scoreDelta": -1.3,
      "momentum3m": 3.85
    },
    {
      "ticker": "APO",
      "name": "Apollo Global Management",
      "sector": "Financials",
      "compositeScore": 38.6,
      "scoreDelta": -1.0,
      "momentum3m": -3.92
    },
    {
      "ticker": "APA",
      "name": "APA Corporation",
      "sector": "Energy",
      "compositeScore": 67.7,
      "scoreDelta": -1.0,
      "momentum3m": 6.57
    },
    {
      "ticker": "PCG",
      "name": "PG&E Corporation",
      "sector": "Utilities",
      "compositeScore": 57.7,
      "scoreDelta": -0.7,
      "momentum3m": 8.97
    },
    {
      "ticker": "OMC",
      "name": "Omnicom Group",
      "sector": "Communication Services",
      "compositeScore": 65.7,
      "scoreDelta": -0.5,
      "momentum3m": 11.8
    }
  ],
  "priceGainers": [
    {
      "ticker": "IT",
      "name": "Gartner",
      "sector": "Information Technology",
      "compositeScore": 65.1,
      "scoreDelta": 0,
      "momentum3m": 16.99
    },
    {
      "ticker": "ZBRA",
      "name": "Zebra Technologies",
      "sector": "Information Technology",
      "compositeScore": 70.0,
      "scoreDelta": 0,
      "momentum3m": 66.57
    },
    {
      "ticker": "PLTR",
      "name": "Palantir Technologies",
      "sector": "Information Technology",
      "compositeScore": 67.6,
      "scoreDelta": 0,
      "momentum3m": 24.83
    },
    {
      "ticker": "CTSH",
      "name": "Cognizant",
      "sector": "Information Technology",
      "compositeScore": 52.9,
      "scoreDelta": 0,
      "momentum3m": 12.38
    },
    {
      "ticker": "ACN",
      "name": "Accenture",
      "sector": "Information Technology",
      "compositeScore": 44.4,
      "scoreDelta": 0,
      "momentum3m": -1.43
    }
  ],
  "priceLosers": [
    {
      "ticker": "SNDK",
      "name": "Sandisk",
      "sector": "Information Technology",
      "compositeScore": 47.5,
      "scoreDelta": 0,
      "momentum3m": -22.41
    },
    {
      "ticker": "APP",
      "name": "AppLovin",
      "sector": "Communication Services",
      "compositeScore": 37.8,
      "scoreDelta": 0,
      "momentum3m": -25.98
    },
    {
      "ticker": "TTD",
      "name": "Trade Desk (The)",
      "sector": "Communication Services",
      "compositeScore": 35.4,
      "scoreDelta": 0,
      "momentum3m": -40.21
    },
    {
      "ticker": "WDC",
      "name": "Western Digital",
      "sector": "Information Technology",
      "compositeScore": 53.2,
      "scoreDelta": 0,
      "momentum3m": -9.5
    },
    {
      "ticker": "HONA",
      "name": "Honeywell Aerospace",
      "sector": "Industrials",
      "compositeScore": null,
      "scoreDelta": 0,
      "momentum3m": null
    }
  ],
  "breadth": {
    "strongBuy": 5,
    "buy": 95,
    "hold": 290,
    "sell": 109,
    "strongSell": 4,
    "avgComposite": 49.9
  },
  "sectors": {
    "Utilities": {
      "avgScore": 43.4,
      "topStock": "D",
      "stockCount": 31,
      "etf": "XLU",
      "etfReturn1m": -3.96,
      "etfReturn3m": -1.86
    },
    "Consumer Discretionary": {
      "avgScore": 48.4,
      "topStock": "EXPE",
      "stockCount": 47,
      "etf": "XLY",
      "etfReturn1m": 2.23,
      "etfReturn3m": -0.08
    },
    "Materials": {
      "avgScore": 47.8,
      "topStock": "CF",
      "stockCount": 26,
      "etf": "XLB",
      "etfReturn1m": 3.87,
      "etfReturn3m": 2.84
    },
    "Consumer Staples": {
      "avgScore": 47.2,
      "topStock": "DLTR",
      "stockCount": 34,
      "etf": "XLP",
      "etfReturn1m": 1.19,
      "etfReturn3m": 1.82
    },
    "Health Care": {
      "avgScore": 51.2,
      "topStock": "DXCM",
      "stockCount": 59,
      "etf": "XLV",
      "etfReturn1m": 3.01,
      "etfReturn3m": 15.97
    },
    "Information Technology": {
      "avgScore": 52.6,
      "topStock": "DELL",
      "stockCount": 73,
      "etf": "XLK",
      "etfReturn1m": 1.18,
      "etfReturn3m": 7.22
    },
    "Communication Services": {
      "avgScore": 46.5,
      "topStock": "GOOG",
      "stockCount": 23,
      "etf": "XLC",
      "etfReturn1m": -0.35,
      "etfReturn3m": -4.62
    },
    "Energy": {
      "avgScore": 55.2,
      "topStock": "VLO",
      "stockCount": 21,
      "etf": "XLE",
      "etfReturn1m": 4.39,
      "etfReturn3m": 3.98
    },
    "Industrials": {
      "avgScore": null,
      "topStock": "ADP",
      "stockCount": 82,
      "etf": "XLI",
      "etfReturn1m": 1.79,
      "etfReturn3m": 7.18
    },
    "Financials": {
      "avgScore": 54.0,
      "topStock": "ALL",
      "stockCount": 76,
      "etf": "XLF",
      "etfReturn1m": 3.39,
      "etfReturn3m": 12.81
    },
    "Real Estate": {
      "avgScore": 48.3,
      "topStock": "BXP",
      "stockCount": 31,
      "etf": "XLRE",
      "etfReturn1m": 1.19,
      "etfReturn3m": 2.17
    }
  }
};
