// Auto-generated by eod_summary.py — do not edit manually
const EOD_DATA = {
  "date": "2026-08-20",
  "generatedAt": "2026-08-20T21:29:10Z",
  "topPick": {
    "ticker": "MPC",
    "name": "Marathon Petroleum",
    "sector": "Energy",
    "price": 358.23,
    "changePct": 0.72,
    "compositeScore": 82.0,
    "technicalScore": 49.0,
    "fundamentalScore": 86.4,
    "momentumScore": 95.3,
    "sectorScore": 100.0,
    "rank": 1,
    "prevRank": 1,
    "signals": {
      "rsi": 69.5,
      "macd": "bullish",
      "bbPct": 0.823,
      "ma50": 294.8,
      "ma200": 230.35,
      "volRatio": 1.02,
      "pe": 12.52,
      "sectorPe": 17.6,
      "epsGrowth": 3.48,
      "revGrowth": 0.537,
      "fcfYield": 0.0913,
      "roe": 0.421,
      "debtEquity": 1.3333,
      "momentum1m": 15.03,
      "momentum3m": 44.59,
      "momentum6m": 83.26,
      "sectorOutperf3m": 36.0
    },
    "thesis": "Marathon Petroleum (MPC) is trading at 12.5x P/E, a 29% discount to its sector average of 17.6x; RSI at 70 reflects strong but extended momentum \u2014 watch for potential consolidation. Three-month price momentum of +44.6% reflects exceptional institutional accumulation, with EPS growing +348% year-on-year, underpinned by a bullish MACD crossover confirming upward price pressure. Composite score of 82/100 places MPC in the top 1% of S&P 500 constituents across all four analytical strategies, outperforming its sector by +36.0% over the past quarter."
  },
  "scoreRisers": [
    {
      "ticker": "PNC",
      "name": "PNC Financial Services",
      "sector": "Financials",
      "compositeScore": 60.5,
      "scoreDelta": 1.1,
      "momentum3m": 11.53
    },
    {
      "ticker": "NOC",
      "name": "Northrop Grumman",
      "sector": "Industrials",
      "compositeScore": 42.9,
      "scoreDelta": 1.0,
      "momentum3m": 2.68
    },
    {
      "ticker": "BAC",
      "name": "Bank of America",
      "sector": "Financials",
      "compositeScore": 70.4,
      "scoreDelta": 0.9,
      "momentum3m": 20.76
    },
    {
      "ticker": "JPM",
      "name": "JPMorgan Chase",
      "sector": "Financials",
      "compositeScore": 67.8,
      "scoreDelta": 0.8,
      "momentum3m": 16.55
    },
    {
      "ticker": "URI",
      "name": "United Rentals",
      "sector": "Industrials",
      "compositeScore": 62.5,
      "scoreDelta": 0.7,
      "momentum3m": 17.7
    }
  ],
  "scoreFallers": [
    {
      "ticker": "CARR",
      "name": "Carrier Global",
      "sector": "Industrials",
      "compositeScore": 23.1,
      "scoreDelta": 0.0,
      "momentum3m": -2.92
    },
    {
      "ticker": "MNST",
      "name": "Monster Beverage",
      "sector": "Consumer Staples",
      "compositeScore": 23.2,
      "scoreDelta": 0.0,
      "momentum3m": -44.98
    },
    {
      "ticker": "TSLA",
      "name": "Tesla, Inc.",
      "sector": "Consumer Discretionary",
      "compositeScore": 24.1,
      "scoreDelta": 0.0,
      "momentum3m": -17.4
    },
    {
      "ticker": "GNRC",
      "name": "Generac",
      "sector": "Industrials",
      "compositeScore": 31.8,
      "scoreDelta": 0.0,
      "momentum3m": -16.56
    },
    {
      "ticker": "PODD",
      "name": "Insulet Corporation",
      "sector": "Health Care",
      "compositeScore": 34.3,
      "scoreDelta": 0.0,
      "momentum3m": -6.39
    }
  ],
  "priceGainers": [
    {
      "ticker": "MRNA",
      "name": "Moderna",
      "sector": "Health Care",
      "compositeScore": 68.0,
      "scoreDelta": 0,
      "momentum3m": 182.1
    },
    {
      "ticker": "WDAY",
      "name": "Workday, Inc.",
      "sector": "Information Technology",
      "compositeScore": 72.6,
      "scoreDelta": 0,
      "momentum3m": 61.94
    },
    {
      "ticker": "IT",
      "name": "Gartner",
      "sector": "Information Technology",
      "compositeScore": 68.7,
      "scoreDelta": 0,
      "momentum3m": 23.19
    },
    {
      "ticker": "CTSH",
      "name": "Cognizant",
      "sector": "Information Technology",
      "compositeScore": 58.2,
      "scoreDelta": 0,
      "momentum3m": 17.12
    },
    {
      "ticker": "NOW",
      "name": "ServiceNow",
      "sector": "Information Technology",
      "compositeScore": 63.7,
      "scoreDelta": 0,
      "momentum3m": 30.15
    }
  ],
  "priceLosers": [
    {
      "ticker": "MNST",
      "name": "Monster Beverage",
      "sector": "Consumer Staples",
      "compositeScore": 23.2,
      "scoreDelta": 0,
      "momentum3m": -44.98
    },
    {
      "ticker": "CHRW",
      "name": "C.H. Robinson",
      "sector": "Industrials",
      "compositeScore": 32.6,
      "scoreDelta": 0,
      "momentum3m": -18.98
    },
    {
      "ticker": "DVA",
      "name": "DaVita",
      "sector": "Health Care",
      "compositeScore": 44.3,
      "scoreDelta": 0,
      "momentum3m": -11.79
    },
    {
      "ticker": "LII",
      "name": "Lennox International",
      "sector": "Industrials",
      "compositeScore": 26.0,
      "scoreDelta": 0,
      "momentum3m": -15.29
    },
    {
      "ticker": "APP",
      "name": "AppLovin",
      "sector": "Communication Services",
      "compositeScore": 36.0,
      "scoreDelta": 0,
      "momentum3m": -36.45
    }
  ],
  "breadth": {
    "strongBuy": 5,
    "buy": 107,
    "hold": 278,
    "sell": 108,
    "strongSell": 5,
    "avgComposite": 50.0
  },
  "sectors": {
    "Utilities": {
      "avgScore": 41.6,
      "topStock": "EIX",
      "stockCount": 31,
      "etf": "XLU",
      "etfReturn1m": -5.24,
      "etfReturn3m": -2.11
    },
    "Health Care": {
      "avgScore": 52.1,
      "topStock": "MRNA",
      "stockCount": 59,
      "etf": "XLV",
      "etfReturn1m": 6.78,
      "etfReturn3m": 16.87
    },
    "Materials": {
      "avgScore": 48.5,
      "topStock": "NEM",
      "stockCount": 25,
      "etf": "XLB",
      "etfReturn1m": 4.24,
      "etfReturn3m": 5.19
    },
    "Energy": {
      "avgScore": 56.3,
      "topStock": "MPC",
      "stockCount": 21,
      "etf": "XLE",
      "etfReturn1m": 7.36,
      "etfReturn3m": 8.59
    },
    "Real Estate": {
      "avgScore": 46.6,
      "topStock": "CBRE",
      "stockCount": 30,
      "etf": "XLRE",
      "etfReturn1m": 0.29,
      "etfReturn3m": 2.19
    },
    "Consumer Discretionary": {
      "avgScore": 49.1,
      "topStock": "EXPE",
      "stockCount": 47,
      "etf": "XLY",
      "etfReturn1m": 7.28,
      "etfReturn3m": -1.51
    },
    "Information Technology": {
      "avgScore": 52.6,
      "topStock": "WDAY",
      "stockCount": 73,
      "etf": "XLK",
      "etfReturn1m": 2.61,
      "etfReturn3m": 2.64
    },
    "Consumer Staples": {
      "avgScore": 47.7,
      "topStock": "TGT",
      "stockCount": 34,
      "etf": "XLP",
      "etfReturn1m": 2.54,
      "etfReturn3m": 1.48
    },
    "Financials": {
      "avgScore": 55.2,
      "topStock": "ALL",
      "stockCount": 76,
      "etf": "XLF",
      "etfReturn1m": 2.01,
      "etfReturn3m": 10.48
    },
    "Industrials": {
      "avgScore": null,
      "topStock": "PAYX",
      "stockCount": 83,
      "etf": "XLI",
      "etfReturn1m": -1.19,
      "etfReturn3m": 5.68
    },
    "Communication Services": {
      "avgScore": 47.7,
      "topStock": "OMC",
      "stockCount": 24,
      "etf": "XLC",
      "etfReturn1m": 5.03,
      "etfReturn3m": -4.42
    }
  }
};
