"""
eod_summary.py — runs at 4:30pm ET weekdays via GitHub Actions.
Reads the final data.js and data_prev.js to compute the end-of-day digest,
writing eod_data.js for the EOD Summary tab.
"""

import json
import os
from datetime import datetime, timezone


def load_json(path):
    if not os.path.exists(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def main():
    data = load_json("data.json")
    prev = load_json("data_prev.json")

    if not data:
        print("data.json not found — aborting.")
        return

    stocks = data.get("stocks", [])
    prev_stocks = {s["ticker"]: s for s in (prev.get("stocks", []) if prev else [])}

    # Top gainers / losers by composite score change vs previous session
    score_moves = []
    for s in stocks:
        cur_score = s["compositeScore"] or 0
        prev_score = prev_stocks.get(s["ticker"], {}).get("compositeScore") or cur_score
        delta = round(cur_score - prev_score, 1)
        score_moves.append({**s, "scoreDelta": delta})

    score_moves.sort(key=lambda x: x["scoreDelta"], reverse=True)
    top_risers = score_moves[:5]
    top_fallers = list(reversed(score_moves[-5:]))

    # Price movers by 1M momentum proxy
    by_momentum = sorted(stocks, key=lambda x: x["signals"].get("momentum1m") or 0, reverse=True)
    price_gainers = by_momentum[:5]
    price_losers = list(reversed(by_momentum[-5:]))

    # Market breadth from scores
    scores = [s["compositeScore"] or 0 for s in stocks]
    strong_buy = sum(1 for sc in scores if sc >= 75)
    buy = sum(1 for sc in scores if 60 <= sc < 75)
    hold = sum(1 for sc in scores if 40 <= sc < 60)
    sell = sum(1 for sc in scores if 25 <= sc < 40)
    strong_sell = sum(1 for sc in scores if sc < 25)

    avg_composite = round(sum(scores) / len(scores), 1) if scores else 0

    def slim(s):
        return {
            "ticker": s["ticker"],
            "name": s["name"],
            "sector": s["sector"],
            "compositeScore": s["compositeScore"],
            "scoreDelta": s.get("scoreDelta", 0),
            "momentum3m": s["signals"].get("momentum3m", 0),
        }

    now_utc = datetime.now(timezone.utc)
    payload = {
        "date": now_utc.strftime("%Y-%m-%d"),
        "generatedAt": now_utc.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "topPick": data.get("topPick", {}),
        "scoreRisers": [slim(s) for s in top_risers],
        "scoreFallers": [slim(s) for s in top_fallers],
        "priceGainers": [slim(s) for s in price_gainers],
        "priceLosers": [slim(s) for s in price_losers],
        "breadth": {
            "strongBuy": strong_buy,
            "buy": buy,
            "hold": hold,
            "sell": sell,
            "strongSell": strong_sell,
            "avgComposite": avg_composite,
        },
        "sectors": data.get("sectors", {}),
    }

    with open("eod_data.js", "w", encoding="utf-8") as f:
        f.write("// Auto-generated by eod_summary.py — do not edit manually\n")
        f.write(f"const EOD_DATA = {json.dumps(payload, indent=2)};\n")

    print(f"eod_data.js written for {now_utc.strftime('%Y-%m-%d')} — top pick: {data.get('topPick', {}).get('ticker', 'N/A')}")


if __name__ == "__main__":
    main()
